# Generated by Django 4.2 on 2023-04-19 10:34

import accounts.managers
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('object', accounts.managers.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('Ж', 'Женщина'), ('Д', 'Другое')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='inform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
